name: 'maturin-action'
description: 'GitHub Action to install and run a custom maturin command'
author: messense

inputs:
  command:
    description: maturin command to run. Defaults to "build".
    required: false
    default: 'build'
  args:
    description: Arguments for the maturin command
    required: false
  maturin-version:
    description: Version of maturin to install like "v0.10.0". Defaults to "latest".
    required: false
    default: 'latest'
  manylinux:
    description: Control the manylinux platform tag on linux.
    required: false
  container:
    description: Docker container image name. Default depends on "target" and "manylinux" options.
    required: false
  target:
    description: The --target option for cargo
    required: false
  rust-toolchain:
    description: |
      Rust toolchain name.
      See https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
    required: false
  rustup-components:
    description: |
      Rustup components.
      See https://rust-lang.github.io/rustup/concepts/components.html
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
