name: Update Versions Manifest

on:
  workflow_dispatch:
  schedule:
    # Run every day at 1:00
    - cron: '0 1 * * *'

permissions: {}

jobs:
  update:
    name: Update Versions Manifest
    runs-on: ubuntu-latest
    permissions:
      contents: write # for push
      pull-requests: write # for PR creation
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.10"
    - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
    - name: Generate Versions Manifest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run generate-versions-manifest.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        branch: update-versions-manifest
        delete-branch: true
        add-paths: |
          versions-manifest.json
        title: 'Update versions-manifest.json'
        commit-message: 'Update versions-manifest.json'
